account/urls.py
from django.conf.urls import url
from account import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
    url(r'^commentCreate/(?P<articleId>[0-9]+)/$', views.commentCreate, name='commentCreate'),
    url(r'^commentUpdate/(?P<commentId>[0-9]+)/$', views.commentUpdate, name='commentUpdate'),
    url(r'^commentDelete/(?P<commentId>[0-9]+)/$', views.commentDelete, name='commentDelete'),
    url(r'^articleLike/(?P<articleId>[0-9]+)/$', views.articleLike, name='articleLike'),
 
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$',  views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


def main(request):
    import datetime
    now = datetime.datetime.now()
    """
    'Django 很棒'
    Render the main page
    """
    context = {'like': 'Django 很棒',
               'time': now}
    return render(request, 'main/main.html', context)


def about(request):
    """
    Render the about page
    """
    return render(request, 'main/about.html')

# Create your views here.

main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
	{% include 'main/menu.html' %}
    <h2>關於 林至丞的部落格</h2>
    <p>歡迎來到林至丞的 部落格,你可以到留言版留言</p>
  </body>
</html>

main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    {% block css %}{% endblock %}
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>部落格 -- {% block heading %}{% endblock %}</h2>
    {% include 'main/messages.html' %}
    {% block content %}{% endblock %}
    {% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% endblock %}
  </body>
</html>

main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
 	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}" charset="utf-8">

  </head>
  <body>
{% include 'main/menu.html' %}
<div>
    <h1><a href="/">林至丞的 Django Blog</a></h1>
    <h1><a href="/main/about/">關於/main/about/</a></h1>
    <h1><a href="{% url 'main:about' %}">關於{% url 'main:about' %}</a></h1>
</div>
    <h2>這是林至丞(Jason)第一次用Django做好的部落格!請大家多多吐槽!</h2>
    <p class="navbar"><h2>這是用 Class 選擇器的例子。</h2>
<p class="navbar"><h2>{{ like }}{{ time }}</h2>
<b class="special">同一個選擇器</b>可以<i class="special">有不同的 instance。</i>
    <p class="applylarge applyred">這是多重 Class 的例子。</p>
    <p id="footer">這是用 ID 選擇器的例子。</p>
    <b class="special">同一個選擇器</b>可以<i class="special">有不同的 instance。</i>
    <div class="large"> 
  這是 DIV 範例。 
</div>
  </body>
</html>

main/templates/main/menu.html
<meta charset="utf-8">
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
  <li><a href="{% url 'article:article' %}">留言板</a></li>
  <li><a href="http://127.0.0.1:8000/admin/">admin</a></li>
  {% if user.is_authenticated %}
    <li><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></li>
  {% else %}
  <li><a href="{% url 'account:register' %}">註冊</a></li>
  <li><a href="{% url 'account:login' %}">登入</a></li>
 {% endif %}
</ul>

main/templates/main/messages.html
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}